### ISSUE TITLE
Upgrading to 3.x

### ISSUE THREAD

**Issue by dereuromark** [mamchenkov/CakePHP-GraphViz-Models#9]
Hi!
I am currently upgrading the plugin to work with 3.x
See
https://github.com/dereuromark/CakePHP-GraphViz-Models

I would like to
- rename plugin to ModelGraph
- license under MIT (to be able to ship with other MIT stuff)

My question:
Any objections from your side regarding the MIT license? Your name will still be included, of course.

**Comment by mamchenkov** [comment]
Hi. 

Had to refresh my memory on the license differences. :) 

No problem at all from my side. Glad you found this useful.

**Comment by mamchenkov** [comment]
@dereuromark 

since I'm not really using this plugin for a while now, would you like to take over? :) I can give you commit access and/or we can transfer it to a different vendor for composer/packagist, etc.

**Comment by dereuromark** [comment]
Whatever suits you is fine.

**Comment by mamchenkov** [comment]
@dereuromark I've added you as collaborator on GitHub and as a maintainer on Packagist. ;)

**Comment by dereuromark** [comment]
Can I take over this at `dereuromark/cakephp-model-graph` ? as composer and packagist name?
This way I can also release a 3.x and 4.x version with the new name there too.

Doing this in the same repo with existing composer name etc wouldnt be a good idea usually.

**Comment by mamchenkov** [comment]
Hey @dereuromark .  Of course :) Do you need anything from me for that?

Thanks!

**Comment by dereuromark** [comment]
Just the confirmation that i can continue with mit license as long as i keep your name in there.

**Comment by mamchenkov** [comment]
@dereuromark you can do whatever you want with it :)  Good luck!
